version: '2'
services:
  grafana:
    restart: unless-stopped
    depends_on:
      - telegraf
    build: ./grafana
    ports:
      - "8080:80"
    environment:
      - GF_SERVER_HTTP_PORT=80
      - GF_PATHS_PROVISIONING=/usr/src/app/provisioning
      - GF_SESSION_PROVIDER=memory
      - GF_INSTALL_PLUGINS=grafana-influxdb-flux-datasource
      - INFLUX_TOKEN
      - INFLUX_ORG
      - INFLUX_BUCKET
      - INFLUX_URL
  sensor:
    build: ./sensor
    privileged: true
    restart: unless-stopped
    environment:
      - BALENASENSE_TEMP_OFFSET
      - BALENASENSE_HUM_OFFSET
      - BALENASENSE_ALTITUDE
  telegraf:
    build: ./telegraf
    restart: unless-stopped
    depends_on:
      - mqtt
    cap_add:
      - SYS_ADMIN
    environment:
      - INFLUX_TOKEN
      - INFLUX_ORG
      - INFLUX_BUCKET
      - INFLUX_URL
      - TELEGRAF_MQTT_URL_PORT=INTERNAL
  mqtt:
    image: eclipse-mosquitto
    ports:
      - "1883"
    restart: unless-stopped
    depends_on:
      - sensor
