{
 "title": "Raspair",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Indoor Air Quality (IAQ) classification",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"#bucket\")\n  |> range($range)\n  |> filter(fn: (r) => r[\"_field\"] == \"air_quality_score\")\n  |> filter(fn: (r) => r[\"host\"] == \"raspair\")"
    }
   ]
  },
  {
   "title": "Indoor Air Quality (IAQ) classification",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 7, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "IAQ" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"#bucket\")\n  |> range($range)\n  |> filter(fn: (r) => r[\"_field\"] == \"air_quality_score\")\n  |> filter(fn: (r) => r[\"host\"] == \"raspair\")"
    }
   ]
  },
  { "title": "Detail", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Humidity",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"#bucket\")\n  |> range($range)\n  |> filter(fn: (r) => r[\"_field\"] == \"humidity\")\n  |> filter(fn: (r) => r[\"host\"] == \"raspair\")"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 7, "y": 8 },
   "yaxes": [
    { "format": "humidity", "label": "Humidity" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"#bucket\")\n  |> range($range)\n  |> filter(fn: (r) => r[\"_field\"] == \"humidity\")\n  |> filter(fn: (r) => r[\"host\"] == \"raspair\")"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 15 },
   "targets": [
    {
     "query": "from(bucket: \"#bucket\")\n  |> range($range)\n  |> filter(fn: (r) => r[\"_field\"] == \"temperature\")\n  |> filter(fn: (r) => r[\"host\"] == \"raspair\")"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 7, "y": 15 },
   "yaxes": [
    { "format": "celsius", "label": "Temperature" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"#bucket\")\n  |> range($range)\n  |> filter(fn: (r) => r[\"_field\"] == \"temperature\")\n  |> filter(fn: (r) => r[\"host\"] == \"raspair\")"
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 22 },
   "targets": [
    {
     "query": "from(bucket: \"#bucket\")\n  |> range($range)\n  |> filter(fn: (r) => r[\"_field\"] == \"pressure\")\n  |> filter(fn: (r) => r[\"host\"] == \"raspair\")"
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 7, "y": 22 },
   "yaxes": [
    { "format": "pressurembar", "label": "mBar" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"#bucket\")\n  |> range($range)\n  |> filter(fn: (r) => r[\"_field\"] == \"pressure\")\n  |> filter(fn: (r) => r[\"host\"] == \"raspair\")"
    }
   ]
  },
  {
   "title": "Indoor Air Quality (IAQ) rating",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 29 },
   "targets": [
    {
     "query": "from(bucket: \"#bucket\")\n  |> range($range)\n  |> filter(fn: (r) => r[\"_field\"] == \"air_quality_score_accuracy\")\n  |> filter(fn: (r) => r[\"host\"] == \"raspair\")"
    }
   ]
  }
 ]
}